// Tech spec §3: tokens are exported from the Figma variables, never retyped.
// Emits CSS custom properties and a Tailwind v4 @theme block.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

const { color } = JSON.parse(readFileSync(new URL("./figma-variables.json", import.meta.url), "utf8"));
const name = (k) => k.replace(/\//g, "-").replace(/-\d-/, "-");
const lines = Object.entries(color).map(([k, v]) => `  --${name(k)}: ${v};`);
// Short utility names for Tailwind: bg-surface, border-line, text-ink-2, text-working …
const ALIAS = {
  "bg/canvas": "canvas", "bg/inset": "inset", "bg/surface": "surface", "bg/elevated": "elevated",
  "border/subtle": "line", "border/strong": "line-strong",
  "text/primary": "ink", "text/secondary": "ink-2", "text/muted": "ink-3",
  "level/1-familiar": "familiar", "level/2-working": "working", "level/3-ready": "ready",
  "accent/blue": "blue", "accent/red": "red",
};
const theme = Object.entries(color).map(([k]) => `  --color-${ALIAS[k] ?? name(k)}: var(--${name(k)});`);
const css = `/* Generated by packages/tokens/build.mjs from figma-variables.json — do not edit. */
:root {
${lines.join("\n")}
}

@theme inline {
${theme.join("\n")}
}
`;

writeFileSync(new URL("./tokens.css", import.meta.url), css);
console.log(`tokens: ${lines.length} colours`);
